/// Flutter icons FlutterDEVICON
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FlutterDEVICON
///      fonts:
///       - asset: fonts/FlutterDEVICON.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class FlutterDEVICON {
  FlutterDEVICON._();

  static const _kFontFam = 'FlutterDEVICON';
  static const String _kFontPkg = null;

  static const IconData recycling_black_24dp = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData recycle = IconData(0xf1b8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
